spring:
  application:
    name: product-service
server:
    port: ${PORT:0}
eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}:${random.int(1000,9999)}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
    fetch-registry: true