spring:
  application:
    name: product-service
server:
    port: ${PORT:0}
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.int(1000,9999)}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/